# Generated by Django 6.0 on 2026-01-05 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tickets', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='priority',
            field=models.CharField(choices=[('MEDIUM', 'Media')], default='MEDIUM', max_length=20, verbose_name='Prioridade'),
        ),
    ]
