# Generated by Django 6.0 on 2026-01-05 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_tickets', '0003_ticket_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='priority',
        ),
    ]
