# Generated by Django 6.0 on 2026-01-05 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tickets', '0006_tickethistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='first_response_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
