# Generated by Django 6.0 on 2025-12-27 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_management', '0003_alter_project_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, verbose_name='Descrição'),
        ),
    ]
