# Generated by Django 6.0 on 2026-01-05 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_management', '0005_project_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='template',
            field=models.TextField(blank=True, help_text='Texto padrão para preencher a descrição do ticket ao selecionar este tópico.', verbose_name='Modelo de Descrição'),
        ),
    ]
