# Generated by Django 6.0 on 2026-01-05 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_management', '0006_topic_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='form_fields',
            field=models.JSONField(blank=True, default=list, help_text='Esquema JSON para campos dinâmicos.', verbose_name='Campos do Formulário'),
        ),
    ]
